# Generated by Django 4.2.5 on 2023-11-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_controller", "0002_alter_equity_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equity",
            name="symbol",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
