# Generated by Django 4.2.5 on 2023-10-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_controller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="equity_symbol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_controller.equitysymbol",
            ),
        ),
    ]
