# Generated by Django 4.2.5 on 2023-10-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_controller", "0002_investment_equity_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="principal_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
