# Generated by Django 4.2.5 on 2023-10-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_controller", "0003_alter_investment_principal_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="principal_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
